name: WebhookIntegrations
version: '${project.version}'
softdepend: [PlaceholderAPI]
main: rudynakodach.github.io.webhookintegrations.WebhookIntegrations
api-version: 1.17
commands:

  seturl:
    usage: /setUrl <url> <?id>
    permission: webhookintegrations.setwebhookurl

  send:
    usage: /send <?target> <isEmbed> <message>
    permission: webhookintegrations.send

  wi:
    usage: /wi
    permission: webhookintegrations.wi
    aliases:
      - "webhookintegrations"
