package rudynakodach.github.io.webhookintegrations.Events;
import java.util.HashMap;

public class AdvancementMap {
    public HashMap<String, String> map = new HashMap<>();

    public AdvancementMap() {
        map.put("husbandry/froglights", "With Our Powers Combined!");
        map.put("nether/distract_piglin", "Oh Shiny");
        map.put("story/obtain_armor", "Suit Up");
        map.put("adventure/very_very_frightening", "Very Very Frightening");
        map.put("story/lava_bucket", "Hot Stuff");
        map.put("husbandry/ride_a_boat_with_a_goat", "Whatever Floats Your Goat!");
        map.put("end/kill_dragon", "Free the End");
        map.put("adventure/lightning_rod_with_villager_no_fire", "Surge Protector");
        map.put("nether/all_potions", "A Furious Cocktail");
        map.put("husbandry/tame_an_animal", "Best Friends Forever");
        map.put("husbandry/make_a_sign_glow", "Glow and Behold!");
        map.put("nether/create_beacon", "Bring Home the Beacon");
        map.put("story/deflect_arrow", "Not Today, Thank You");
        map.put("husbandry/leash_all_frog_variants", "When the Squad Hops into Town");
        map.put("nether/brew_potion", "Local Brewery");
        map.put("end/dragon_egg", "The Next Generation");
        map.put("adventure/kill_mob_near_sculk_catalyst", "It Spreads");
        map.put("husbandry/fishy_business", "Fishy Business");
        map.put("nether/explore_nether", "Hot Tourist Destinations");
        map.put("nether/ride_strider", "This Boat Has Legs");
        map.put("adventure/sniper_duel", "Sniper Duel");
        map.put("end/levitate", "Great View From Up Here");
        map.put("adventure/bullseye", "Bullseye");
        map.put("nether/get_wither_skull", "Spooky Scary Skeleton");
        map.put("husbandry/bred_all_animals", "Two by Two");
        map.put("story/mine_stone", "Stone Age");
        map.put("adventure/two_birds_one_arrow", "Two Birds, One Arrow");
        map.put("story/enter_the_nether", "We Need to Go Deeper");
        map.put("story/upgrade_tools", "Getting an Upgrade");
        map.put("adventure/walk_on_powder_snow_with_leather_boots", "Light as a Rabbit");
        map.put("husbandry/tactical_fishing", "Tactical Fishing");
        map.put("story/cure_zombie_villager", "Zombie Doctor");
        map.put("end/find_end_city", "The City at the End of the Game");
        map.put("story/form_obsidian", "Ice Bucket Challenge");
        map.put("end/enter_end_gateway", "Remote Getaway");
        map.put("nether/obtain_blaze_rod", "Into Fire");
        map.put("nether/loot_bastion", "War Pigs");
        map.put("adventure/shoot_arrow", "Take Aim");
        map.put("husbandry/silk_touch_nest", "Total Beelocation");
        map.put("adventure/arbalistic", "Arbalistic");
        map.put("end/respawn_dragon", "The End... Again...");
        map.put("story/smelt_iron", "Acquire Hardware");
        map.put("story/shiny_gear", "Cover Me with Diamonds");
        map.put("husbandry/tadpole_in_a_bucket", "Bukkit Bukkit");
        map.put("husbandry/wax_off", "Wax Off");
        map.put("adventure/summon_iron_golem", "Hired Help");
        map.put("nether/return_to_sender", "Return to Sender");
        map.put("adventure/sleep_in_bed", "Sweet Dreams");
        map.put("end/dragon_breath", "You Need a Mint");
        map.put("adventure/kill_all_mobs", "Monsters Hunted");
        map.put("story/enchant_item", "Enchanter");
        map.put("adventure/voluntary_exile", "Voluntary Exile");
        map.put("story/follow_ender_eye", "Eye Spy");
        map.put("husbandry/obtain_netherite_hoe", "Serious Dedication");
        map.put("adventure/totem_of_undying", "Postmortal");
        map.put("adventure/kill_a_mob", "Monster Hunter");
        map.put("adventure/adventuring_time", "Adventuring Time");
        map.put("husbandry/plant_seed", "A Seedy Place");
        map.put("nether/find_bastion", "Those Were the Days");
        map.put("husbandry/axolotl_in_a_bucket", "The Cutest Predator");
        map.put("husbandry/allay_deliver_cake_to_note_block", "Birthday Song");
        map.put("nether/ride_strider_in_overworld_lava", "Feels Like Home");
        map.put("adventure/trade_at_world_height", "Star Trader");
        map.put("husbandry/wax_on", "Wax On");
        map.put("adventure/play_jukebox_in_meadows", "Sound of Music");
        map.put("adventure/hero_of_the_village", "Hero of the Village");
        map.put("nether/obtain_ancient_debris", "Hidden in the Depths");
        map.put("nether/create_full_beacon", "Beaconator");
        map.put("nether/summon_wither", "Withering Heights");
        map.put("husbandry/balanced_diet", "A Balanced Diet");
        map.put("nether/fast_travel", "Subspace Bubble");
        map.put("nether/use_lodestone", "Country Lode, Take Me Home");
        map.put("husbandry/safely_harvest_honey", "Bee Our Guest");
        map.put("adventure/trade", "What a Deal!");
        map.put("nether/uneasy_alliance", "Uneasy Alliance");
        map.put("story/mine_diamond", "Diamonds!");
        map.put("husbandry/kill_axolotl_target", "The Healing Power of Friendship!");
        map.put("nether/find_fortress", "A Terrible Fortress");
        map.put("adventure/throw_trident", "A Throwaway Joke");
        map.put("adventure/honey_block_slide", "Sticky Situation");
        map.put("nether/netherite_armor", "Cover Me in Debris");
        map.put("husbandry/breed_an_animal", "The Parrots and the Bats");
        map.put("husbandry/complete_catalogue", "A Complete Catalogue");
    }
}
